site_name: ALS Tables Manager
theme:
  name: null
  custom_dir: cinder
nav:
- Home: index.md
- ALS Sctructure: als_structure.md
- Functions: Functions.md
markdown_extensions:
  - attr_list
  - md_in_html


